[theme]
primaryColor = "#E91E63"          # Accent (buttons, highlights)
backgroundColor = "#FFFFFF"       # App background
secondaryBackgroundColor = "#F5F5F5" # Sidebar or cards
textColor = "#1F1F1F"             # Default text
font = "sans serif"               # Options: sans serif, serif, monospace
